version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "test/build.gradle" }}
      - run:
          name: "Image Information"
          command: printf "\nKernel:\n " && uname -a && printf "\n\nMemory:\n " && free -h && printf "\n\nStorage:\n" && df -h
      - run:
          name: "Chmod gradlew"
          command: sudo chmod +x ./gradlew
      - run:
          name: "Download Dependencies"
          command: ./gradlew androidDependencies
      - run:
          name: "Update Dependencies"
          command: ./gradlew dependencyUpdates
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "test/build.gradle" }}
      - run:
          name: "Build Modules"
          command: ./gradlew build
      - run:
          name: "Run Tests"
          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: library/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: library/build/test-results