version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: "Image Information"
          command: printf "\nKernel " && uname -a && printf "\nMemory " && free -h && printf "\nStorage" && df -h
      - run:
          name: "Chmod gradlew"
          command: sudo chmod +x ./gradlew
      - run:
          name: "Download Dependencies"
          command: ./gradlew dependencyUpdates
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "test/build.gradle" }}
      - run:
          name: "Build Modules"
          command: ./gradlew build
      - run:
          name: "Run Gradle check"
          command: ./gradlew check
      - run:
          name: "Run Tests"
          command: ./gradlew test