version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: "Chmod permissions"
          command: sudo chmod +x ./gradlew
      - run:
          name: "Copy SDK License"
          command: printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > ~/android-sdk-linux/licenses/android-sdk-license
      - run:
          name: "Download Dependencies"
          command: ./gradlew dependencyUpdates
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: "Build Modules"
          command: ./gradlew build
      - run:
          name: "Jacoco Test Report"
          command: ./gradlew jacocoTestReport
      - run:
          name: "CodeCov"
          command: bash <(curl -s https://codecov.io/bash)